apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: user-service-build-
spec:
  pipelineRef:
    name: capstone-build-deploy
  taskRunTemplate:
    serviceAccountName: pipeline
  params:
    - name: GIT_URL
      value: https://github.com/riyazXcode/ecommerce-capstone.git
    - name: GIT_REVISION
      value: main
    - name: CONTEXT_DIR
      value: services/user-service
    - name: BUILDCONFIG
      value: user-service
    - name: DEPLOYMENT_NAME
      value: user-service
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
