apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: image-registry.openshift-image-registry.svc:5000/riyazkhan03-dev/user-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: DB_URL
              value: jdbc:postgresql://user-db:5432/userdb
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: user-db-credentials, key: POSTGRESQL_USER } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: user-db-credentials, key: POSTGRESQL_PASSWORD } }
            - name: JWT_SECRET
              valueFrom: { secretKeyRef: { name: user-service-jwt, key: JWT_SECRET } }
          resources:
            requests: { cpu: 100m, memory: 384Mi }
            limits: { cpu: 500m, memory: 512Mi }
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8083 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8083 }
            initialDelaySeconds: 40
            periodSeconds: 20
